;;; gruber-material-dark.el --- Soft dark themes based on Gruber Darker -*- lexical-binding: t; -*-

;; Copyright (C) 2025-2026 Vostranox

;; Author: Vostranox <vostranox@gmail.com>
;; Maintainer: Vostranox <vostranox@gmail.com>
;; URL: https://github.com/Vostranox/gruber-material-dark
;; Version: 1.1
;; Package-Requires: ((emacs "27.1"))
;; Keywords: faces
;; SPDX-License-Identifier: MIT

;;; Commentary:

;; This package provides two dark themes: `gruber-material-dark' and
;; `gruber-material-dark-intense'.  They are softer, Material-flavored
;; variants of Gruber Darker.
;;
;; Based on gruber-darker-theme by Alexey Kutepov a.k.a. rexim
;; (https://github.com/rexim/gruber-darker-theme), itself derived from
;; Jason Blevins' Gruber Dark theme for BBEdit.

;;; Code:

(defun gruber-material-dark--lookup (palette key)
  "Return the color associated with KEY in PALETTE."
  (cdr (assq key palette)))

(defun gruber-material-dark--apply-faces (theme palette)
  "Set the face specifications of THEME using the colors in PALETTE."
  (let* ((pg (lambda (k) (gruber-material-dark--lookup palette k)))
         (fg0       (funcall pg 'gruber-material-dark-fg0))
         (bg0       (funcall pg 'gruber-material-dark-bg0))
         (bg0-5     (funcall pg 'gruber-material-dark-bg0-5))
         (bg1       (funcall pg 'gruber-material-dark-bg1))
         (bg2       (funcall pg 'gruber-material-dark-bg2))
         (bg3       (funcall pg 'gruber-material-dark-bg3))
         (bg4       (funcall pg 'gruber-material-dark-bg4))
         (bg-red    (funcall pg 'gruber-material-dark-bg-red))
         (red       (funcall pg 'gruber-material-dark-red))
         (bg-green  (funcall pg 'gruber-material-dark-bg-green))
         (green     (funcall pg 'gruber-material-dark-green))
         (bg-yellow (funcall pg 'gruber-material-dark-bg-yellow))
         (yellow    (funcall pg 'gruber-material-dark-yellow))
         (brown     (funcall pg 'gruber-material-dark-brown))
         (bg-quartz (funcall pg 'gruber-material-dark-bg-quartz))
         (quartz0   (funcall pg 'gruber-material-dark-quartz0))
         (quartz1   (funcall pg 'gruber-material-dark-quartz1))
         (niagara0  (funcall pg 'gruber-material-dark-niagara0))
         (niagara1  (funcall pg 'gruber-material-dark-niagara1))
         (niagara2  (funcall pg 'gruber-material-dark-niagara2))
         (wisteria  (funcall pg 'gruber-material-dark-wisteria)))

    (custom-theme-set-faces
     theme

     `(default ((t (:foreground ,fg0 :background ,bg0))))
     `(region ((t (:background ,bg2))))
     `(highlight ((t (:background ,bg2))))
     `(cursor ((t (:foreground ,bg0 :background ,yellow))))
     `(hl-line ((t (:foreground unspecified :background unspecified))))
     `(vertical-border ((t (:foreground ,bg2))))
     `(internal-border ((t (:background ,bg0))))
     `(window-divider ((t (:foreground ,bg2))))
     `(minibuffer-prompt ((t (:foreground ,niagara2 :weight bold))))
     `(secondary-selection ((t (:background ,bg1))))
     `(fringe ((t (:foreground ,fg0 :background ,bg0))))
     `(header-line ((t (:foreground ,fg0 :background ,bg1))))
     `(link ((t (:foreground ,niagara2 :underline t))))
     `(link-visited ((t (:foreground ,wisteria :underline t))))
     `(shadow ((t (:foreground ,quartz0))))
     `(help-key-binding ((t (:foreground ,quartz1))))
     `(bookmark-face ((t (:foreground ,quartz1))))
     `(escape-glyph ((t (:foreground ,quartz1))))
     `(homoglyph ((t (:foreground ,quartz1))))
     `(success ((t (:foreground ,green))))
     `(warning ((t (:foreground ,yellow))))
     `(error ((t (:foreground ,red))))
     `(bold ((t (:weight bold))))
     `(bold-italic ((t (:weight bold :slant italic))))
     `(italic ((t (:slant italic))))
     `(underline ((t (:underline t))))
     `(info-node ((t (:foreground ,red :background ,bg0))))
     `(info-menu-star ((t (:foreground ,red :background ,bg0))))

     `(line-number ((t (:foreground ,bg4 :background ,bg0))))
     `(line-number-current-line ((t (:foreground ,yellow :background ,bg0))))

     `(trailing-whitespace ((t (:foreground ,bg1 :background ,bg0))))

     `(whitespace-space ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-hspace ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-newline ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-line ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-trailing ((t (:foreground ,red :background ,bg0))))
     `(whitespace-indentation ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-tab ((t (:foreground ,quartz0 :background ,bg0))))
     `(whitespace-space-after-tab ((t (:foreground ,quartz0 :background ,bg0))))
     `(whitespace-space-before-tab ((t (:foreground ,quartz0 :background ,bg0))))
     `(whitespace-missing-newline-at-eof ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-empty ((t (:foreground ,red :background ,bg-yellow))))

     `(show-paren-match ((t(:foreground ,wisteria :background ,bg2 :weight bold))))
     `(show-paren-match-expression ((t(:foreground ,red :background ,bg2 :weight bold))))
     `(show-paren-mismatch ((t(:foreground ,red :background ,bg2 :weight bold))))

     `(mode-line-buffer-id ((t (:foreground ,quartz1 :background ,bg0-5))))
     `(mode-line ((t (:foreground ,fg0 :background ,bg0-5 :box (:line-width 1 :color ,niagara0 :style nil)))))
     `(mode-line-active ((t (:foreground ,fg0 :background ,bg0-5 :box (:line-width 1 :color ,niagara0 :style nil)))))
     `(mode-line-inactive ((t (:foreground ,niagara1 :background ,bg0 :box (:line-width 1 :color ,bg1 :style nil)))))

     `(match ((t (:foreground ,green))))
     `(lazy-highlight ((t (:foreground ,fg0 :background ,quartz0))))

     `(isearch ((t (:foreground ,bg0 :background ,fg0))))
     `(isearch-fail ((t (:foreground ,bg0 :background ,red))))
     `(isearch-group-1 ((t (:background ,bg0))))
     `(isearch-group-2 ((t (:background ,bg0))))

     `(font-lock-bracket-face ((t (:foreground ,fg0))))
     `(font-lock-builtin-face ((t (:foreground ,yellow))))
     `(font-lock-comment-face ((t (:foreground ,brown))))
     `(font-lock-comment-delimiter-face ((t (:foreground ,brown))))
     `(font-lock-constant-face ((t (:foreground ,quartz1))))
     `(font-lock-delimiter-face ((t (:foreground ,fg0))))
     `(font-lock-doc-face ((t (:foreground ,green))))
     `(font-lock-doc-markup-face ((t (:foreground ,green))))
     `(font-lock-escape-face ((t (:foreground ,red))))
     `(font-lock-function-name-face ((t (:foreground ,niagara2))))
     `(font-lock-function-call-face ((t (:foreground ,niagara2))))
     `(font-lock-keyword-face ((t (:foreground ,yellow))))
     `(font-lock-misc-punctuation-face ((t (:foreground ,fg0))))
     `(font-lock-negation-char-face ((t (:foreground ,red))))
     `(font-lock-number-face ((t (:foreground ,fg0))))
     `(font-lock-operator-face ((t (:foreground ,fg0))))
     `(font-lock-preprocessor-face ((t (:foreground ,quartz1))))
     `(font-lock-property-name-face ((t (:foreground ,fg0))))
     `(font-lock-property-use-face ((t (:foreground ,fg0))))
     `(font-lock-punctuation-face ((t (:foreground ,fg0))))
     `(font-lock-regexp-face ((t (:foreground ,quartz1))))
     `(font-lock-regexp-grouping-backslash ((t (:foreground ,yellow))))
     `(font-lock-regexp-grouping-construct ((t (:foreground ,yellow))))
     `(font-lock-string-face ((t (:foreground ,green))))
     `(font-lock-type-face ((t (:foreground ,quartz1))))
     `(font-lock-variable-name-face ((t (:foreground ,fg0))))
     `(font-lock-variable-use-face ((t (:foreground ,fg0))))
     `(font-lock-warning-face ((t (:foreground ,red))))

     `(sh-heredoc ((t (:foreground ,wisteria))))
     `(sh-quoted-exec ((t (:foreground ,quartz1))))

     `(completions-highlight ((t (:background ,bg1))))
     `(completions-common-part ((t (:inherit match))))
     `(completions-annotations ((t (:foreground ,quartz1 :background ,bg0))))
     `(completions-group-title ((t (:foreground ,quartz1 :background ,bg0))))
     `(completions-group-separator ((t (:foreground ,quartz1 :background ,bg0))))
     `(completions-first-difference ((t (:foreground ,yellow :weight bold))))

     `(completion-preview ((t (:foreground ,quartz0))))
     `(completion-preview-common ((t (:foreground ,quartz0))))
     `(completion-preview-exact ((t (:foreground ,green))))

     `(company-echo ((t (:foreground ,fg0))))
     `(company-echo-common ((t (:foreground ,red))))
     `(company-preview ((t (:background ,bg0-5))))
     `(company-template-field ((t (:foreground ,yellow))))
     `(company-tooltip ((t (:background ,bg0-5))))
     `(company-tooltip-scrollbar-thumb ((t (:background ,bg0-5))))
     `(company-tooltip-scrollbar-track ((t (:background ,bg0-5))))
     `(company-tooltip-search ((t (:background ,bg1))))
     `(company-tooltip-search-selection ((t (:background ,bg1))))
     `(company-tooltip-selection ((t (:background ,bg1))))
     `(company-preview-common ((t (:inherit match))))
     `(company-preview-search ((t (:inherit match))))
     `(company-tooltip-common ((t (:inherit match))))
     `(company-tooltip-common-selection ((t (:inherit match))))
     `(company-tooltip-annotation ((t (:foreground ,niagara2))))
     `(company-tooltip-annotation-selection ((t (:foreground ,niagara2))))
     `(company-tooltip-quick-access ((t (:foreground ,niagara2))))
     `(company-tooltip-quick-access-selection ((t (:foreground ,niagara2))))
     `(company-posframe-quickhelp ((t (:inherit corfu-default))))

     `(corfu-default ((t (:foreground ,fg0 :background ,bg0-5))))
     `(corfu-current ((t (:foreground ,fg0 :background ,bg1))))
     `(corfu-bar ((t (:background ,bg1))))
     `(corfu-border ((t (:background ,bg0-5))))
     `(corfu-annotations ((t (:foreground ,niagara2))))
     `(corfu-deprecated ((t (:foreground ,fg0 :strike-through t))))
     `(corfu-candidate-overlay-face ((t (:foreground ,brown :background ,bg0-5))))
     `(corfu-candidate-overlay-face-exact-match ((t (:foreground ,brown :background ,bg1 :underline t))))

     `(ido-first-match ((t (:foreground ,fg0))))
     `(ido-only-match ((t (:foreground ,green))))
     `(ido-subdir ((t (:inherit dired-directory))))
     `(ido-virtual ((t (:foreground ,wisteria))))
     `(ido-incomplete-regexp ((t (:inherit warning))))
     `(ido-indicator ((t (:foreground ,fg0 :weight bold))))

     `(vertico-current ((t (:background ,bg1))))
     `(vertico-group-title ((t (:foreground ,quartz1))))
     `(vertico-group-separator ((t (:foreground ,quartz1 :strike-through ,bg2))))

     `(vertico-posframe ((t (:foreground ,fg0 :background ,bg0))))
     `(vertico-posframe-border ((t (:background ,quartz0))))

     `(orderless-match-face-0 ((t (:inherit match))))
     `(orderless-match-face-1 ((t (:inherit match))))
     `(orderless-match-face-2 ((t (:inherit match))))
     `(orderless-match-face-3 ((t (:inherit match))))

     `(prescient-primary-highlight ((t (:inherit match))))
     `(prescient-secondary-highlight ((t (:inherit match))))

     `(compilation-info ((t (:foreground ,quartz1))))
     `(compilation-line-number ((t (:foreground ,quartz1))))
     `(compilation-column-number ((t (:foreground ,quartz1))))
     `(compilation-mode-line-exit ((t (:foreground ,quartz1))))
     `(compilation-warning ((t (:foreground ,yellow))))
     `(compilation-mode-line-run ((t (:foreground ,wisteria))))
     `(compilation-error ((t (:foreground ,red))))
     `(compilation-mode-line-fail ((t (:foreground ,red))))

     `(consult-preview-match ((t (:inherit lazy-highlight))))
     `(consult-file ((t (:foreground ,fg0))))
     `(consult-highlight-mark ((t (:foreground ,fg0 :background ,bg2))))
     `(consult-highlight-match ((t (:inherit match))))
     `(consult-preview-insertion ((t (:foreground ,fg0 :background ,bg1))))
     `(consult-preview-line ((t (:background ,bg1))))
     `(consult-key ((t (:foreground ,fg0 :background ,bg1))))
     `(consult-help ((t (:foreground ,fg0 :background ,bg1))))
     `(consult-grep-context ((t (:foreground ,quartz1 :background ,bg1))))
     `(consult-line-number ((t (:foreground ,quartz1))))
     `(consult-line-number-prefix ((t (:foreground ,quartz1))))
     `(consult-line-number-wrapped ((t (:foreground ,quartz1))))
     `(consult-narrow-indicator ((t (:foreground ,quartz1))))

     `(mc/cursor-face ((t (:foreground ,bg0 :background ,yellow))))
     `(mc/region-face ((t (:inherit region))))

     `(vr/group-0 ((t (:foreground ,bg0 :background ,green))))
     `(vr/group-1 ((t (:foreground ,bg0 :background ,niagara2))))
     `(vr/group-2 ((t (:foreground ,bg0 :background ,wisteria))))

     `(vr/match-0 ((t (:foreground ,bg0 :background ,quartz1))))
     `(vr/match-1 ((t (:foreground ,bg0 :background ,quartz1))))
     `(vr/match-separator-face ((t (:foreground ,bg0 :background ,red))))

     `(avy-background-face ((t (:background ,bg0))))
     `(avy-lead-face ((t (:foreground ,yellow :background ,bg2))))
     `(avy-lead-face-0 ((t (:foreground ,yellow :background ,bg2))))
     `(avy-lead-face-1 ((t (:foreground ,yellow :background ,bg2))))
     `(avy-lead-face-2 ((t (:foreground ,yellow :background ,bg2))))
     `(avy-goto-char-timer-face ((t (:inherit lazy-highlight))))

     `(dired-broken-symlink ((t (:foreground ,red :background ,bg0))))
     `(dired-directory ((t (:foreground ,quartz1 :background ,bg0))))
     `(dired-flagged ((t (:foreground ,red :background ,bg0))))
     `(dired-header ((t (:foreground ,niagara2 :background ,bg0))))
     `(dired-ignored ((t (:foreground ,fg0 :background ,bg0))))
     `(dired-mark ((t (:foreground ,quartz1 :background ,bg0))))
     `(dired-marked ((t (:foreground ,yellow :background ,bg0))))
     `(dired-perm-write ((t (:foreground ,fg0 :background ,bg0))))
     `(dired-set-id ((t (:foreground ,fg0 :background ,bg0))))
     `(dired-special ((t (:foreground ,fg0 :background ,bg0))))
     `(dired-symlink ((t (:foreground ,wisteria :background ,bg0))))
     `(dired-warning ((t (:foreground ,yellow :background ,bg0))))

     `(diredfl-symlink ((t (:foreground ,wisteria))))
     `(diredfl-dir-name ((t (:foreground ,quartz1))))
     `(diredfl-dir-heading ((t (:foreground ,niagara2))))
     `(diredfl-file-name ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-file-suffix ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-deletion ((t (:foreground ,red :background ,bg0))))
     `(diredfl-deletion-file-name ((t (:foreground ,red :background ,bg0))))
     `(diredfl-number ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-date-time ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-flag-mark ((t (:foreground ,yellow :background ,bg0))))
     `(diredfl-flag-mark-line ((t (:foreground ,yellow :background ,bg0))))
     `(diredfl-dir-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-read-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-write-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-exec-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-link-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-no-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-autofile-name ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-compressed-file-name ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-compressed-file-suffix ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-ignored-file-name ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-executable-tag ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-other-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-rare-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-tagged-autofile-name ((t (:foreground ,fg0 :background ,bg0))))

     `(outline-1 ((t (:foreground ,quartz1))))
     `(outline-2 ((t (:foreground ,niagara2))))
     `(outline-3 ((t (:foreground ,wisteria))))
     `(outline-4 ((t (:foreground ,green))))
     `(outline-5 ((t (:foreground ,quartz1))))
     `(outline-6 ((t (:foreground ,niagara2))))
     `(outline-7 ((t (:foreground ,wisteria))))
     `(outline-8 ((t (:foreground ,green))))

     `(org-document-title ((t (:inherit outline-1 :height 1.1))))
     `(org-level-1 ((t (:inherit outline-1 :height 1.1))))
     `(org-level-2 ((t (:inherit outline-2 :height 1.0))))
     `(org-level-3 ((t (:inherit outline-3 :height 1.0))))
     `(org-level-4 ((t (:inherit outline-4 :height 1.0))))
     `(org-level-5 ((t (:inherit outline-5 :height 1.0))))
     `(org-level-6 ((t (:inherit outline-6 :height 1.0))))
     `(org-level-7 ((t (:inherit outline-7 :height 1.0))))
     `(org-level-8 ((t (:inherit outline-8 :height 1.0))))
     `(org-link ((t (:foreground ,quartz1 :underline ,quartz1))))
     `(org-todo ((t (:foreground ,red))))
     `(org-done ((t (:foreground ,niagara2 :weight bold))))
     `(org-warning ((t (:foreground ,yellow))))
     `(org-hide ((t (:foreground ,bg0))))
     `(org-special-keyword ((t (:inherit font-lock-comment-face))))
     `(org-drawer ((t (:inherit font-lock-function-name-face))))
     `(org-column ((t (:background ,bg0))))
     `(org-column-title ((t (:background ,bg0 :underline t :weight bold))))
     `(org-archived ((t (:foreground ,fg0 :weight bold))))
     `(org-footnote ((t (:foreground ,niagara2 :underline t))))
     `(org-ellipsis ((t (:foreground ,quartz1))))
     `(org-date ((t (:foreground ,quartz1 :underline t))))
     `(org-sexp-date ((t (:foreground ,quartz1 :underline t))))
     `(org-tag ((t (:weight bold))))
     `(org-list-dt ((t (:weight bold))))
     `(org-agenda-done ((t (:foreground ,niagara2))))
     `(org-headline-done ((t (:foreground ,niagara2))))
     `(org-table ((t (:foreground ,quartz1))))
     `(org-block ((t (:background ,bg0))))
     `(org-block-begin-line ((t (:foreground ,quartz0 :background ,bg0))))
     `(org-block-end-line ((t (:foreground ,quartz0 :background ,bg0))))
     `(org-formula ((t (:foreground ,wisteria))))
     `(org-document-info ((t (:foreground ,quartz1))))
     `(org-agenda-structure ((t (:inherit font-lock-comment-face))))
     `(org-agenda-date-today ((t (:foreground ,fg0 :weight bold :slant italic))))
     `(org-scheduled ((t (:foreground ,wisteria))))
     `(org-scheduled-today ((t (:foreground ,quartz1))))
     `(org-scheduled-previously ((t (:foreground ,red))))
     `(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
     `(org-deadline-announce ((t (:foreground ,red))))
     `(org-time-grid ((t (:foreground ,quartz1))))
     `(org-latex-and-related ((t (:foreground ,quartz1))))
     `(org-code ((t (:foreground ,quartz1))))
     `(org-verbatim ((t (:foreground ,quartz1))))
     `(org-quote ((t (:foreground ,brown :slant italic))))
     `(org-checkbox ((t (:foreground ,yellow))))
     `(org-priority ((t (:foreground ,red))))
     `(org-meta-line ((t (:foreground ,quartz0))))
     `(org-headline-todo ((t (:foreground ,fg0))))
     `(org-agenda-date ((t (:foreground ,niagara2))))
     `(org-agenda-date-weekend ((t (:foreground ,quartz1))))
     `(org-agenda-current-time ((t (:foreground ,yellow))))

     `(markdown-ts-heading-1 ((t (:inherit outline-1))))
     `(markdown-ts-heading-2 ((t (:inherit outline-2))))
     `(markdown-ts-heading-3 ((t (:inherit outline-3))))
     `(markdown-ts-heading-4 ((t (:inherit outline-4))))
     `(markdown-ts-heading-5 ((t (:inherit outline-5))))
     `(markdown-ts-heading-6 ((t (:inherit outline-6))))

     `(markdown-header-face-1 ((t (:inherit outline-1))))
     `(markdown-header-face-2 ((t (:inherit outline-2))))
     `(markdown-header-face-3 ((t (:inherit outline-3))))
     `(markdown-header-face-4 ((t (:inherit outline-4))))
     `(markdown-header-face-5 ((t (:inherit outline-5))))
     `(markdown-header-face-6 ((t (:inherit outline-6))))
     `(markdown-url-face ((t (:foreground ,niagara2))))
     `(markdown-plain-url-face ((t (:foreground ,niagara2))))
     `(markdown-code-face ((t (:foreground ,quartz1))))
     `(markdown-inline-code-face ((t (:foreground ,quartz1))))
     `(markdown-pre-face ((t (:foreground ,quartz1))))
     `(markdown-markup-face ((t (:foreground ,quartz0))))
     `(markdown-header-delimiter-face ((t (:foreground ,quartz0))))
     `(markdown-language-keyword-face ((t (:foreground ,quartz0))))
     `(markdown-metadata-key-face ((t (:foreground ,quartz0))))
     `(markdown-metadata-value-face ((t (:foreground ,fg0))))
     `(markdown-bold-face ((t (:weight bold))))
     `(markdown-italic-face ((t (:slant italic))))
     `(markdown-list-face ((t (:foreground ,yellow))))
     `(markdown-blockquote-face ((t (:foreground ,brown :slant italic))))
     `(markdown-link-face ((t (:foreground ,niagara2 :underline t))))
     `(markdown-table-face ((t (:foreground ,quartz1))))

     `(git-commit-summary ((t (:foreground ,fg0))))
     `(git-commit-overlong-summary ((t (:foreground ,quartz1))))
     `(git-commit-nonempty-second-line ((t (:foreground ,red))))

     `(magit-header-line ((t (:foreground ,yellow))))
     `(magit-section-heading ((t (:foreground ,yellow))))
     `(magit-branch-remote ((t (:foreground ,green))))
     `(magit-branch-local ((t (:foreground ,niagara2))))
     `(magit-branch-current ((t (:underline ,niagara2 :inherit magit-branch-local))))
     `(magit-diff-added ((t (:foreground ,green))))
     `(magit-diff-added-highlight ((t (:foreground ,green :background ,bg1))))
     `(magit-diff-removed ((t (:foreground ,red))))
     `(magit-diff-removed-highlight ((t (:foreground ,red :background ,bg1))))
     `(magit-diff-base ((t (:foreground ,wisteria :background ,bg0))))
     `(magit-diff-base-highlight ((t (:foreground ,wisteria :background ,bg0))))
     `(magit-diff-context ((t (:foreground ,fg0))))
     `(magit-diff-context-highlight ((t (:foreground ,fg0 :background ,bg0))))
     `(magit-diff-hunk-heading ((t (:foreground ,fg0 :background ,bg1))))
     `(magit-diff-hunk-heading-highlight ((t (:foreground ,fg0 :background ,bg2))))
     `(magit-diff-hunk-heading-selection ((t (:foreground ,fg0 :background ,bg1))))
     `(magit-diff-lines-boundary ((t (:foreground ,wisteria :background ,bg0))))
     `(magit-diff-lines-heading ((t (:foreground ,wisteria :background ,bg0))))
     `(magit-diff-whitespace-warning ((t (:foreground ,red :background ,bg0))))
     `(magit-diff-file-heading-selection ((t (:foreground ,quartz1 :background ,bg0))))
     `(magit-diffstat-added ((t (:foreground ,green))))
     `(magit-diffstat-removed ((t (:foreground ,red))))
     `(magit-process-ok ((t (:foreground ,green))))
     `(magit-process-ng ((t (:foreground ,red))))
     `(magit-log-author ((t (:foreground ,red))))
     `(magit-log-date ((t (:foreground ,quartz1))))
     `(magit-log-graph ((t (:foreground ,bg3))))
     `(magit-log-message ((t (:foreground ,fg0))))
     `(magit-reflog-cherry-pick ((t (:foreground ,green))))
     `(magit-reflog-commit ((t (:foreground ,green))))
     `(magit-reflog-merge ((t (:foreground ,green))))
     `(magit-reflog-reset ((t (:foreground ,red))))
     `(magit-reflog-amend ((t (:foreground ,wisteria))))
     `(magit-reflog-checkout ((t (:foreground ,niagara2))))
     `(magit-reflog-other ((t (:foreground ,quartz1))))
     `(magit-reflog-rebase ((t (:foreground ,wisteria))))
     `(magit-reflog-remote ((t (:foreground ,niagara2))))
     `(magit-sequence-stop ((t (:foreground ,green))))
     `(magit-sequence-drop ((t (:foreground ,wisteria))))
     `(magit-sequence-head ((t (:foreground ,quartz1))))
     `(magit-sequence-part ((t (:foreground ,wisteria))))
     `(magit-signature-good ((t (:foreground ,green))))
     `(magit-signature-bad ((t (:foreground ,red))))
     `(magit-signature-error ((t (:foreground ,red))))
     `(magit-signature-expired ((t (:foreground ,wisteria))))
     `(magit-signature-revoked ((t (:foreground ,wisteria))))
     `(magit-signature-untrusted ((t (:foreground ,niagara2))))
     `(magit-bisect-bad ((t (:foreground ,red))))
     `(magit-bisect-good ((t (:foreground ,green))))
     `(magit-bisect-skip ((t (:foreground ,wisteria))))
     `(magit-mode-line-process-error ((t (:foreground ,red))))
     `(magit-blame-heading ((t (:foreground ,brown :background ,bg1))))
     `(magit-cherry-equivalent ((t (:foreground ,wisteria))))
     `(magit-cherry-unmatched ((t (:foreground ,quartz1))))
     `(magit-dimmed ((t (:foreground ,bg3))))
     `(magit-hash ((t (:foreground ,niagara2))))
     `(magit-refname ((t (:foreground ,brown))))
     `(magit-section-heading-selection ((t (:foreground ,wisteria))))
     `(magit-section-highlight ((t (:background ,bg1))))
     `(magit-tag ((t (:foreground ,wisteria))))
     `(magit-diff-our-heading ((t (:foreground ,red :background ,bg1))))
     `(magit-diff-base-heading ((t (:foreground ,wisteria :background ,bg1))))
     `(magit-diff-their-heading ((t (:foreground ,green :background ,bg1))))

     `(diff-header ((t (:foreground ,fg0 :background ,bg2))))
     `(diff-error ((t (:foreground ,red :background ,bg2))))
     `(diff-file-header ((t (:foreground ,fg0 :background ,bg2))))
     `(diff-hunk-header ((t (:foreground ,fg0 :background ,bg2))))
     `(diff-context ((t (:background ,bg0))))
     `(diff-added ((t (:foreground ,green :background ,bg0))))
     `(diff-removed ((t (:foreground ,red :background ,bg0))))
     `(diff-changed ((t (:foreground ,yellow :background ,bg0))))
     `(diff-refine-added ((t (:background ,bg-green))))
     `(diff-refine-changed ((t (:background ,bg-green))))
     `(diff-refine-removed ((t (:background ,bg-red))))
     `(diff-indicator-added ((t (:foreground ,green))))
     `(diff-indicator-removed ((t (:foreground ,red))))

     `(diff-hl-insert ((t (:foreground ,green :background ,bg0))))
     `(diff-hl-delete ((t (:foreground ,red :background ,bg0))))
     `(diff-hl-change ((t (:foreground ,yellow :background ,bg0))))
     `(diff-hl-reference-insert ((t (:foreground ,green :background ,bg-green))))
     `(diff-hl-reference-delete ((t (:foreground ,red :background ,bg-red))))
     `(diff-hl-reference-change ((t (:foreground ,yellow :background ,bg-yellow))))
     `(diff-hl-dired-insert ((t (:foreground ,green :background ,bg0))))
     `(diff-hl-dired-delete ((t (:foreground ,red :background ,bg0))))
     `(diff-hl-dired-change ((t (:foreground ,yellow :background ,bg0))))
     `(diff-hl-dired-unknown ((t (:foreground ,quartz0 :background ,bg0))))
     `(diff-hl-dired-ignored ((t (:foreground ,quartz0 :background ,bg0))))
     `(diff-hl-reverted-hunk-highlight ((t (:foreground ,bg0 :background ,yellow))))

     `(ediff-current-diff-Ancestor ((t (:foreground ,quartz1 :background ,bg1))))
     `(ediff-current-diff-A ((t (:foreground ,red :background ,bg1))))
     `(ediff-current-diff-B ((t (:foreground ,green :background ,bg1))))
     `(ediff-current-diff-C ((t (:foreground ,yellow :background ,bg1))))
     `(ediff-fine-diff-Ancestor ((t (:foreground ,quartz1 :background ,bg-quartz))))
     `(ediff-fine-diff-A ((t (:foreground ,red :background ,bg-red))))
     `(ediff-fine-diff-B ((t (:foreground ,green :background ,bg-green))))
     `(ediff-fine-diff-C ((t (:foreground ,yellow :background ,bg-yellow))))
     `(ediff-even-diff-Ancestor ((t (:foreground ,quartz1 :background ,bg0))))
     `(ediff-even-diff-A ((t (:foreground ,red :background ,bg0))))
     `(ediff-even-diff-B ((t (:foreground ,green :background ,bg0))))
     `(ediff-even-diff-C ((t (:foreground ,yellow :background ,bg0))))
     `(ediff-odd-diff-Ancestor ((t (:foreground ,quartz1 :background ,bg0))))
     `(ediff-odd-diff-A ((t (:foreground ,red :background ,bg0))))
     `(ediff-odd-diff-B ((t (:foreground ,green :background ,bg0))))
     `(ediff-odd-diff-C ((t (:foreground ,yellow :background ,bg0))))

     `(smerge-upper ((t (:foreground ,red :background ,bg1 :extend t))))
     `(smerge-lower ((t (:foreground ,green :background ,bg1 :extend t))))
     `(smerge-base ((t (:foreground ,quartz1 :background ,bg1 :extend t))))
     `(smerge-markers ((t (:foreground ,quartz0 :background ,bg0 :weight bold :extend t))))
     `(smerge-refined-removed ((t (:foreground ,red :background ,bg-red :extend t))))
     `(smerge-refined-added ((t (:foreground ,green :background ,bg-green :extend t))))
     `(smerge-refined-changed ((t (:foreground ,yellow :background ,bg-yellow :extend t))))

     `(eglot-mode-line ((t (:foreground ,quartz1 :weight medium))))
     `(eglot-highlight-symbol-face ((t (:weight medium))))
     `(eglot-inlay-hint-face ((t (:foreground ,quartz0 :height 0.9))))
     `(eglot-type-hint-face ((t (:inherit eglot-inlay-hint-face))))
     `(eglot-parameter-hint-face ((t (:inherit eglot-inlay-hint-face))))
     `(eglot-diagnostic-tag-unnecessary-face ((t (:foreground ,quartz0))))
     `(eglot-diagnostic-tag-deprecated-face ((t (:strike-through t))))

     `(eldoc-highlight-function-argument ((t (:foreground ,yellow :weight bold))))

     `(flycheck-error ((t (:underline (:style wave :color ,red)))))
     `(flycheck-warning ((t (:underline (:style wave :color ,yellow)))))
     `(flycheck-info ((t (:underline (:style wave :color ,niagara2)))))
     `(flycheck-fringe-warning ((t (:foreground ,yellow))))
     `(flycheck-fringe-error ((t (:foreground ,red))))
     `(flycheck-fringe-info ((t (:foreground ,niagara2))))
     `(flycheck-error-list-warning ((t (:foreground ,yellow :weight bold))))
     `(flycheck-error-list-error ((t (:foreground ,red :weight bold))))
     `(flycheck-error-list-info ((t (:foreground ,niagara2 :weight bold))))

     `(flymake-error ((t (:underline (:style wave :color ,red)))))
     `(flymake-warning ((t (:underline (:style wave :color ,yellow)))))
     `(flymake-note ((t (:underline (:style wave :color ,niagara2)))))
     `(flymake-error-echo ((t (:foreground ,red))))
     `(flymake-warning-echo ((t (:foreground ,yellow))))
     `(flymake-note-echo ((t (:foreground ,niagara2))))
     `(flymake-end-of-line-diagnostics-face ((t (:height 0.9 :box (:line-width -1 :color ,bg2)))))
     `(flymake-error-echo-at-eol ((t (:foreground ,red))))
     `(flymake-warning-echo-at-eol ((t (:foreground ,yellow))))
     `(flymake-note-echo-at-eol ((t (:foreground ,niagara2))))

     `(flyspell-incorrect ((t (:underline (:style wave :color ,red)))))
     `(flyspell-duplicate ((t (:underline (:style wave :color ,yellow)))))

     `(wgrep-file-face ((t (:background ,bg2))))
     `(wgrep-reject-face ((t (:foreground ,red))))
     `(wgrep-delete-face ((t (:strike-through ,red))))
     `(wgrep-done-face ((t (:foreground ,niagara2))))
     `(wgrep-face ((t (:foreground ,fg0))))

     `(vundo-highlight ((t (:foreground ,green))))
     `(vundo-saved ((t (:foreground ,yellow))))
     `(vundo-last-saved ((t (:foreground ,red))))

     `(minibuffer-depth-indicator ((t (:background ,bg1))))
     `(minibuffer-nonselected ((t (:background ,bg1))))
     `(persp-selected-face ((t (:foreground ,quartz1))))
     `(marginalia-documentation ((t (:foreground ,fg0 :italic t))))

     `(buffer-menu-buffer ((t (:weight medium))))

     `(popper-echo-area ((t (:foreground ,fg0 :background ,bg0))))
     `(popper-echo-area-buried ((t (:foreground ,fg0 :background ,bg0))))
     `(popper-echo-dispatch-hint ((t (:foreground ,fg0 :background ,bg0))))

     `(p4-action-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-branch-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-change-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-client-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-depot-add-face ((t (:foreground ,green :background ,bg0))))
     `(p4-depot-branch-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-depot-delete-face ((t (:foreground ,red :background ,bg0))))
     `(p4-depot-edit-face ((t (:foreground ,yellow :background ,bg0))))
     `(p4-description-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-filespec-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-form-comment-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-form-keyword-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-heading-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-job-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-label-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-link-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-revision-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-user-face ((t (:foreground ,fg0 :background ,bg0))))

     `(eshell-prompt ((t (:foreground ,quartz1))))
     `(eshell-ls-archive ((t (:foreground ,fg0))))
     `(eshell-ls-backup ((t (:foreground ,brown))))
     `(eshell-ls-clutter ((t (:foreground ,wisteria))))
     `(eshell-ls-directory ((t (:foreground ,niagara2))))
     `(eshell-ls-executable ((t (:weight bold))))
     `(eshell-ls-missing ((t (:foreground ,red))))
     `(eshell-ls-product ((t (:foreground ,red))))
     `(eshell-ls-readonly ((t (:foreground ,fg0))))
     `(eshell-ls-special ((t (:foreground ,wisteria))))
     `(eshell-ls-symlink ((t (:foreground ,wisteria))))
     `(eshell-ls-unreadable ((t (:foreground ,red))))

     `(term-color-black ((t (:foreground ,bg3 :background ,bg1))))
     `(term-color-red ((t (:foreground ,red :background ,red))))
     `(term-color-green ((t (:foreground ,green :background ,green))))
     `(term-color-blue ((t (:foreground ,niagara2 :background ,niagara2))))
     `(term-color-yellow ((t (:foreground ,yellow :background ,yellow))))
     `(term-color-magenta ((t (:foreground ,wisteria :background ,wisteria))))
     `(term-color-cyan ((t (:foreground ,quartz1 :background ,quartz1))))
     `(term-color-white ((t (:foreground ,fg0 :background ,fg0))))

     `(ansi-color-black ((t (:foreground ,bg3 :background ,bg1))))
     `(ansi-color-red ((t (:foreground ,red :background ,red))))
     `(ansi-color-yellow ((t (:foreground ,yellow :background ,yellow))))
     `(ansi-color-green ((t (:foreground ,green :background ,green))))
     `(ansi-color-blue ((t (:foreground ,niagara2 :background ,niagara2))))
     `(ansi-color-magenta ((t (:foreground ,wisteria :background ,wisteria))))
     `(ansi-color-cyan ((t (:foreground ,quartz1 :background ,quartz1))))
     `(ansi-color-white ((t (:foreground ,fg0 :background ,fg0))))
     `(ansi-color-bright-black ((t (:foreground ,bg3 :background ,bg1))))
     `(ansi-color-bright-red ((t (:foreground ,red :background ,red))))
     `(ansi-color-bright-yellow ((t (:foreground ,yellow :background ,yellow))))
     `(ansi-color-bright-green ((t (:foreground ,green :background ,green))))
     `(ansi-color-bright-blue ((t (:foreground ,niagara2 :background ,niagara2))))
     `(ansi-color-bright-magenta ((t (:foreground ,wisteria :background ,wisteria))))
     `(ansi-color-bright-cyan ((t (:foreground ,quartz1 :background ,quartz1))))
     `(ansi-color-bright-white ((t (:foreground ,fg0 :background ,fg0))))

     `(xref-file-header ((t (:foreground ,quartz1))))
     `(xref-line-number ((t (:foreground ,quartz1))))
     `(xref-match ((t (:inherit match))))

     `(next-error ((t (:inherit region))))
     `(next-error-message ((t (:background ,bg1))))
     `(pulse-highlight-start-face ((t (:background ,bg2))))

     `(hi-yellow ((t (:foreground ,fg0 :background ,bg-yellow))))
     `(hi-pink ((t (:foreground ,fg0 :background ,bg-red))))
     `(hi-green ((t (:foreground ,fg0 :background ,bg-green))))
     `(hi-blue ((t (:foreground ,fg0 :background ,niagara0))))
     `(hi-salmon ((t (:foreground ,fg0 :background ,bg-quartz))))
     `(hi-aquamarine ((t (:foreground ,fg0 :background ,bg2))))
     `(hi-black-b ((t (:foreground ,fg0 :weight bold))))
     `(hi-blue-b ((t (:foreground ,niagara2 :weight bold))))
     `(hi-green-b ((t (:foreground ,green :weight bold))))
     `(hi-red-b ((t (:foreground ,red :weight bold))))
     `(hi-black-hb ((t (:foreground ,fg0 :weight bold))))

     `(nxml-element-local-name ((t (:foreground ,quartz1))))
     `(css-selector ((t (:foreground ,niagara2))))
     `(css-property ((t (:foreground ,fg0))))

     `(rust-unsafe-face ((t (:foreground ,red))))
     `(rust-question-mark-face ((t (:foreground ,yellow))))
     `(rust-builtin-formatting-macro-face ((t (:foreground ,quartz1))))
     `(rust-string-interpolation-face ((t (:inherit font-lock-string-face :slant italic))))

     `(haskell-constructor-face ((t (:foreground ,quartz1))))
     `(haskell-operator-face ((t (:foreground ,fg0))))
     `(haskell-pragma-face ((t (:foreground ,quartz0))))
     `(haskell-keyword-face ((t (:inherit font-lock-keyword-face))))

     `(meow-normal-indicator ((t (:foreground ,yellow :weight bold))))
     `(meow-insert-indicator ((t (:foreground ,green :weight bold))))
     `(meow-motion-indicator ((t (:foreground ,niagara2 :weight bold))))
     `(meow-keypad-indicator ((t (:foreground ,wisteria :weight bold))))
     `(meow-beacon-indicator ((t (:foreground ,red :weight bold))))
     `(meow-search-indicator ((t (:foreground ,quartz1 :weight bold))))
     `(meow-position-highlight-number-1 ((t (:foreground ,fg0 :background ,bg2 :weight bold))))
     `(meow-position-highlight-number-2 ((t (:foreground ,fg0 :background ,bg2 :weight bold))))
     `(meow-position-highlight-number-3 ((t (:foreground ,fg0 :background ,bg2 :weight bold))))
     `(meow-search-highlight ((t (:inherit lazy-highlight))))
     `(meow-beacon-fake-cursor ((t (:foreground ,bg0 :background ,yellow))))
     `(meow-beacon-fake-selection ((t (:inherit region))))
     `(meow-region-cursor-1 ((t (:inherit cursor))))
     `(meow-region-cursor-2 ((t (:inherit cursor))))
     `(meow-region-cursor-3 ((t (:inherit cursor))))
     `(meow-keypad-cursor ((t (:background ,bg2))))
     `(meow-grab-highlight ((t (:background ,bg2))))

     `(embark-keybinding ((t (:foreground ,quartz1))))
     `(embark-target ((t (:inherit highlight))))
     `(embark-collect-group-title ((t (:foreground ,quartz1))))
     `(embark-collect-group-separator ((t (:foreground ,quartz1))))
     `(embark-collect-marked ((t (:foreground ,yellow))))
     `(embark-verbose-indicator-title ((t (:foreground ,fg0 :weight bold))))
     `(embark-verbose-indicator-documentation ((t (:inherit marginalia-documentation))))

     `(vc-dir-header ((t (:foreground ,quartz1))))
     `(vc-dir-header-value ((t (:foreground ,fg0))))
     `(vc-dir-directory ((t (:inherit dired-directory))))
     `(vc-dir-file ((t (:foreground ,fg0))))
     `(vc-dir-mark-indicator ((t (:foreground ,yellow))))
     `(vc-dir-status-edited ((t (:foreground ,yellow))))
     `(vc-dir-status-up-to-date ((t (:foreground ,green))))
     `(vc-dir-status-ignored ((t (:foreground ,quartz0))))
     `(vc-dir-status-warning ((t (:foreground ,red))))
     `(log-view-message ((t (:foreground ,fg0))))
     `(log-view-file ((t (:foreground ,quartz1))))
     `(log-view-commit-body ((t (:foreground ,fg0))))
     `(log-edit-header ((t (:foreground ,quartz1))))
     `(log-edit-summary ((t (:foreground ,fg0))))
     `(log-edit-unknown-header ((t (:foreground ,red))))

     `(which-key-key-face ((t (:foreground ,quartz1))))
     `(which-key-separator-face ((t (:foreground ,quartz0))))
     `(which-key-command-description-face ((t (:foreground ,fg0))))
     `(which-key-group-description-face ((t (:foreground ,niagara2))))
     `(which-key-local-map-description-face ((t (:foreground ,fg0))))
     `(which-key-special-key-face ((t (:foreground ,yellow))))
     `(which-key-note-face ((t (:foreground ,quartz0))))
     `(which-key-highlighted-command-face ((t (:foreground ,yellow))))
     `(which-key-docstring-face ((t (:foreground ,quartz0))))

     `(tab-bar ((t (:foreground ,fg0 :background ,bg0-5))))
     `(tab-bar-tab ((t (:foreground ,fg0 :background ,bg1 :box (:line-width 1 :color ,niagara0 :style nil)))))
     `(tab-bar-tab-inactive ((t (:foreground ,niagara1 :background ,bg0-5))))
     `(tab-bar-tab-group-current ((t (:foreground ,quartz1 :background ,bg0-5 :weight bold))))
     `(tab-bar-tab-group-inactive ((t (:foreground ,niagara1 :background ,bg0-5))))
     `(tab-bar-tab-ungrouped ((t (:foreground ,niagara1 :background ,bg0-5))))
     `(tab-line ((t (:foreground ,fg0 :background ,bg0-5))))
     `(tab-line-tab ((t (:foreground ,fg0 :background ,bg1 :box (:line-width 1 :color ,niagara0 :style nil)))))
     `(tab-line-tab-current ((t (:foreground ,fg0 :background ,bg1 :box (:line-width 1 :color ,niagara0 :style nil)))))
     `(tab-line-tab-inactive ((t (:foreground ,niagara1 :background ,bg0-5))))
     `(tab-line-highlight ((t (:background ,bg2))))
     `(tab-line-close-highlight ((t (:foreground ,red))))

     `(widget-field ((t (:foreground ,fg0 :background ,bg1))))
     `(widget-single-line-field ((t (:foreground ,fg0 :background ,bg1))))
     `(widget-button ((t (:weight bold))))
     `(widget-documentation ((t (:foreground ,green))))
     `(custom-button ((t (:foreground ,fg0 :background ,bg1 :box (:line-width 1 :color ,bg2 :style nil)))))
     `(custom-button-mouse ((t (:foreground ,fg0 :background ,bg2 :box (:line-width 1 :color ,bg3 :style nil)))))
     `(custom-button-pressed ((t (:foreground ,fg0 :background ,bg2 :box (:line-width 1 :color ,bg3 :style nil)))))
     `(custom-variable-tag ((t (:foreground ,niagara2 :weight bold))))
     `(custom-face-tag ((t (:foreground ,niagara2 :weight bold))))
     `(custom-group-tag ((t (:foreground ,quartz1 :weight bold :height 1.1))))
     `(custom-state ((t (:foreground ,green))))
     `(custom-changed ((t (:foreground ,bg0 :background ,niagara2))))
     `(custom-modified ((t (:foreground ,bg0 :background ,niagara2))))
     `(custom-invalid ((t (:foreground ,bg0 :background ,red))))

     `(info-title-1 ((t (:inherit outline-1 :height 1.2 :weight bold))))
     `(info-title-2 ((t (:inherit outline-2 :height 1.1 :weight bold))))
     `(info-title-3 ((t (:inherit outline-3 :weight bold))))
     `(info-title-4 ((t (:inherit outline-4 :weight bold))))
     `(info-header-node ((t (:foreground ,red :weight bold))))
     `(info-header-xref ((t (:inherit link))))
     `(info-xref ((t (:inherit link))))
     `(info-xref-visited ((t (:inherit link-visited))))

     `(comint-highlight-prompt ((t (:foreground ,quartz1))))
     `(comint-highlight-input ((t (:foreground ,fg0))))

     `(Man-overstrike ((t (:foreground ,yellow :weight bold))))
     `(Man-underline ((t (:foreground ,green :underline t))))
     `(Man-reverse ((t (:inherit highlight))))
     `(woman-bold ((t (:foreground ,yellow :weight bold))))
     `(woman-italic ((t (:foreground ,green :slant italic))))

     `(mode-line-emphasis ((t (:weight bold))))
     `(mode-line-highlight ((t (:box (:line-width 1 :color ,bg2 :style nil)))))
     `(header-line-highlight ((t (:background ,bg2))))
     `(tooltip ((t (:foreground ,fg0 :background ,bg0-5))))
     `(child-frame-border ((t (:background ,bg2))))

     `(package-name ((t (:foreground ,niagara2))))
     `(package-description ((t (:foreground ,fg0))))
     `(package-status-installed ((t (:foreground ,green))))
     `(package-status-available ((t (:foreground ,fg0))))
     `(package-status-built-in ((t (:foreground ,quartz1))))
     `(package-status-new ((t (:foreground ,green :weight bold))))
     `(package-status-dependency ((t (:foreground ,quartz0))))
     `(package-status-avail-obso ((t (:foreground ,quartz0))))
     `(package-status-unsigned ((t (:foreground ,yellow))))
     `(package-status-incompat ((t (:foreground ,red))))

     `(epa-mark ((t (:foreground ,yellow :weight bold))))
     `(epa-string ((t (:foreground ,green))))
     `(epa-field-name ((t (:foreground ,quartz1 :weight bold))))
     `(epa-field-body ((t (:foreground ,fg0))))
     `(epa-validity-high ((t (:foreground ,green))))
     `(epa-validity-medium ((t (:foreground ,yellow))))
     `(epa-validity-low ((t (:foreground ,red))))
     `(epa-validity-disabled ((t (:foreground ,quartz0))))

     `(calendar-today ((t (:foreground ,yellow :weight bold))))
     `(calendar-weekday-header ((t (:foreground ,quartz1))))
     `(calendar-weekend-header ((t (:foreground ,niagara2))))
     `(calendar-month-header ((t (:foreground ,fg0 :weight bold))))
     `(holiday ((t (:foreground ,fg0 :background ,bg-red))))
     `(diary ((t (:foreground ,wisteria))))

     `(transient-heading ((t (:foreground ,fg0))))
     `(transient-key ((t (:foreground ,quartz1))))
     `(transient-key-stack ((t (:foreground ,quartz1))))
     `(transient-key-stay ((t (:foreground ,niagara2))))
     `(transient-key-recurse ((t (:foreground ,niagara2))))
     `(transient-key-exit ((t (:foreground ,niagara2))))
     `(transient-argument ((t (:foreground ,quartz1))))
     `(transient-value ((t (:foreground ,quartz1))))
     `(transient-inactive-argument ((t (:foreground ,bg4))))
     `(transient-inactive-value ((t (:foreground ,bg3))))
     `(transient-unreachable ((t (:foreground ,bg3))))
     `(transient-unreachable-key ((t (:foreground ,bg3))))
     `(transient-nonstandard-key ((t (:foreground ,wisteria))))
     `(transient-mismatched-key ((t (:foreground ,red))))
     `(transient-enabled-suffix ((t (:foreground ,quartz1))))
     `(transient-disabled-suffix ((t (:foreground ,bg4))))
     `(transient-separator ((t (:foreground ,bg4))))
     `(transient-key-return ((t (:foreground ,yellow)))))))

(defmacro gruber-material-dark-deftheme (name doc palette)
  "Define a theme named NAME with docstring DOC.
The theme faces are built from the colors in PALETTE."
  `(progn
     (deftheme ,name ,doc)
     (gruber-material-dark--apply-faces ',name ,palette)
     (provide-theme ',name)))

(provide 'gruber-material-dark)

;;; gruber-material-dark.el ends here
