;;; -*- lexical-binding: t; coding: utf-8 -*-

(eval-when-compile (require 'cl-lib))

(defun gruber-material--lookup (palette key)
  (cdr (assq key palette)))

(defun gruber-material--apply-faces (theme palette)
  (let* ((pg (lambda (k) (gruber-material--lookup palette k)))
         (white     (funcall pg 'gruber-material-dark-white))
         (black     (funcall pg 'gruber-material-dark-black))
         (fg0       (funcall pg 'gruber-material-dark-fg0))
         (bg0       (funcall pg 'gruber-material-dark-bg0))
         (bg0-5     (funcall pg 'gruber-material-dark-bg0-5))
         (bg1       (funcall pg 'gruber-material-dark-bg1))
         (bg2       (funcall pg 'gruber-material-dark-bg2))
         (bg3       (funcall pg 'gruber-material-dark-bg3))
         (bg4       (funcall pg 'gruber-material-dark-bg4))
         (bg-red    (funcall pg 'gruber-material-dark-bg-red))
         (red       (funcall pg 'gruber-material-dark-red))
         (bg-green  (funcall pg 'gruber-material-dark-bg-green))
         (green     (funcall pg 'gruber-material-dark-green))
         (bg-yellow (funcall pg 'gruber-material-dark-bg-yellow))
         (yellow    (funcall pg 'gruber-material-dark-yellow))
         (brown     (funcall pg 'gruber-material-dark-brown))
         (bg-quartz (funcall pg 'gruber-material-dark-bg-quartz))
         (quartz0   (funcall pg 'gruber-material-dark-quartz0))
         (quartz1   (funcall pg 'gruber-material-dark-quartz1))
         (niagara0  (funcall pg 'gruber-material-dark-niagara0))
         (niagara1  (funcall pg 'gruber-material-dark-niagara1))
         (niagara2  (funcall pg 'gruber-material-dark-niagara2))
         (wisteria  (funcall pg 'gruber-material-dark-wisteria)))

    (custom-theme-set-faces
     theme

     `(default ((t (:foreground ,fg0 :background ,bg0))))
     `(region ((t (:background ,bg2))))
     `(highlight ((t (:background ,bg2))))
     `(cursor ((t (:foreground ,bg0 :background ,yellow))))
     `(hl-line ((t (:foreground unspecified :background unspecified))))
     `(vertical-border ((t (:foreground ,bg2))))
     `(internal-border ((t (:foreground ,bg2))))
     `(window-divider ((t (:foreground ,bg2))))
     `(minibuffer-prompt ((t (:foreground ,niagara2 :weight bold))))
     `(secondary-selection ((t (:background ,bg1))))
     `(fringe ((t (:foreground ,fg0 :background ,bg0))))
     `(header-line ((t (:foreground ,fg0 :background ,bg1))))
     `(link ((t (:foreground ,fg0))))
     `(shadow ((t (:foreground ,quartz0))))
     `(help-key-binding ((t (:foreground ,quartz1))))
     `(bookmark-face ((t (:foreground ,quartz1))))
     `(escape-glyph ((t (:foreground ,quartz1))))
     `(homoglyph ((t (:foreground ,quartz1))))
     `(success ((t (:foreground ,green))))
     `(warning ((t (:foreground ,yellow))))
     `(error ((t (:foreground ,red))))
     `(bold ((t (:weight bold))))
     `(bold-italic ((t (:weight bold :slant italic))))
     `(italic ((t (:slant italic))))
     `(underline ((t (:underline t))))
     `(info-node ((t (:foreground ,red :background ,bg0))))
     `(info-menu-star ((t (:foreground ,red :background ,bg0))))

     `(line-number ((t (:foreground ,bg4 :background ,bg0))))
     `(line-number-current-line ((t (:foreground ,yellow :background ,bg0))))

     `(trailing-whitespace ((t (:foreground ,bg1 :background ,bg0))))

     `(whitespace-space ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-hspace ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-newline ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-line ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-trailing ((t (:foreground ,red :background ,bg0))))
     `(whitespace-indentation ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-tab ((t (:foreground ,quartz0 :background ,bg0))))
     `(whitespace-space-after-tab ((t (:foreground ,quartz0 :background ,bg0))))
     `(whitespace-space-before-tab ((t (:foreground ,quartz0 :background ,bg0))))
     `(whitespace-missing-newline-at-eof ((t (:foreground ,bg1 :background ,bg0))))
     `(whitespace-empty ((t (:foreground ,red :background ,bg-yellow))))

     `(show-paren-match ((t(:foreground ,wisteria :background ,bg2 :weight bold))))
     `(show-paren-match-expression ((t(:foreground ,red :background ,bg2 :weight bold))))
     `(show-paren-mismatch ((t(:foreground ,red :background ,bg2 :weight bold))))

     `(mode-line-buffer-id ((t (:foreground ,quartz1 :background ,bg0-5))))
     `(mode-line ((t (:foreground ,fg0 :background ,bg0-5 :box (:line-width 1 :color ,niagara0 :style nil)))))
     `(mode-line-active ((t (:foreground ,fg0 :background ,bg0-5 :box (:line-width 1 :color ,niagara0 :style nil)))))
     `(mode-line-inactive ((t (:foreground ,niagara1 :background ,bg0 :box (:line-width 1 :color ,bg1 :style nil)))))

     `(match ((t (:foreground ,green))))
     `(lazy-highlight ((t (:foreground ,fg0 :background ,quartz0))))

     `(isearch ((t (:foreground ,bg0 :background ,fg0))))
     `(isearch-fail ((t (:foreground ,bg0 :background ,red))))
     `(isearch-group-1 ((t (:background ,bg0))))
     `(isearch-group-2 ((t (:background ,bg0))))

     `(font-lock-bracket-face ((t (:foreground ,fg0))))
     `(font-lock-builtin-face ((t (:foreground ,yellow))))
     `(font-lock-comment-face ((t (:foreground ,brown))))
     `(font-lock-comment-delimiter-face ((t (:foreground ,brown))))
     `(font-lock-constant-face ((t (:foreground ,quartz1))))
     `(font-lock-delimiter-face ((t (:foreground ,fg0))))
     `(font-lock-doc-face ((t (:foreground ,green))))
     `(font-lock-doc-markup-face ((t (:foreground ,green))))
     `(font-lock-escape-face ((t (:foreground ,red))))
     `(font-lock-function-name-face ((t (:foreground ,niagara2))))
     `(font-lock-function-call-face ((t (:foreground ,niagara2))))
     `(font-lock-keyword-face ((t (:foreground ,yellow))))
     `(font-lock-misc-punctuation-face ((t (:foreground ,fg0))))
     `(font-lock-negation-char-face ((t (:foreground ,red))))
     `(font-lock-number-face ((t (:foreground ,fg0))))
     `(font-lock-operator-face ((t (:foreground ,fg0))))
     `(font-lock-preprocessor-face ((t (:foreground ,quartz1))))
     `(font-lock-property-name-face ((t (:foreground ,fg0))))
     `(font-lock-property-use-face ((t (:foreground ,fg0))))
     `(font-lock-punctuation-face ((t (:foreground ,fg0))))
     `(font-lock-regexp-face ((t (:foreground ,quartz1))))
     `(font-lock-regexp-grouping-backslash ((t (:foreground ,yellow))))
     `(font-lock-regexp-grouping-construct ((t (:foreground ,yellow))))
     `(font-lock-string-face ((t (:foreground ,green))))
     `(font-lock-type-face ((t (:foreground ,quartz1))))
     `(font-lock-variable-name-face ((t (:foreground ,fg0))))
     `(font-lock-variable-use-face ((t (:foreground ,fg0))))
     `(font-lock-warning-face ((t (:foreground ,red))))

     `(sh-heredoc ((t (:foreground ,wisteria))))
     `(sh-quoted-exec ((t (:foreground ,quartz1))))

     `(completions-highlight ((t (:background ,bg1))))
     `(completions-common-part ((t (:inherit match))))
     `(completions-annotations ((t (:foreground ,quartz1 :background ,bg0))))
     `(completions-group-title ((t (:foreground ,quartz1 :background ,bg0))))
     `(completions-group-separator ((t (:foreground ,quartz1 :background ,bg0))))

     `(company-echo ((t (:foreground ,fg0))))
     `(company-echo-common ((t (:foreground ,red))))
     `(company-preview ((t (:background ,bg0-5))))
     `(company-preview-common ((t (:foreground ,green))))
     `(company-preview-search ((t (:foreground ,green))))
     `(company-template-field ((t (:foreground ,yellow))))
     `(company-tooltip ((t (:background ,bg0-5))))
     `(company-tooltip-common ((t (:foreground ,green))))
     `(company-tooltip-common-selection ((t (:foreground ,green))))
     `(company-tooltip ((t (:background ,bg0-5))))
     `(company-tooltip-scrollbar-thumb ((t (:background ,bg0-5))))
     `(company-tooltip-scrollbar-track ((t (:background ,bg0-5))))
     `(company-tooltip-search ((t (:background ,bg1))))
     `(company-tooltip-search-selection ((t (:background ,bg1))))
     `(company-tooltip-selection ((t (:background ,bg1))))
     `(company-preview-common ((t (:inherit match))))
     `(company-preview-search ((t (:inherit match))))
     `(company-tooltip-common ((t (:inherit match))))
     `(company-tooltip-common-selection ((t (:inherit match))))
     `(company-tooltip-annotation ((t (:foreground ,niagara2))))
     `(company-tooltip-annotation-selection ((t (:foreground ,niagara2))))
     `(company-tooltip-quick-access ((t (:foreground ,niagara2))))
     `(company-tooltip-quick-access-selection ((t (:foreground ,niagara2))))

     `(corfu-default ((t (:foreground ,fg0 :background ,bg0-5))))
     `(corfu-current ((t (:foreground ,fg0 :background ,bg1))))
     `(corfu-bar ((t (:background ,bg1))))
     `(corfu-border ((t (:background ,bg0-5))))
     `(corfu-annotations ((t (:foreground ,niagara2))))
     `(corfu-deprecated ((t (:foreground ,fg0 :strike-through t))))
     `(corfu-candidate-overlay-face ((t (:foreground ,brown :background ,bg0-5))))
     `(corfu-candidate-overlay-face-exact-match ((t (:foreground ,brown :background ,bg1 :underline t))))

     `(ido-first-match ((t (:foreground ,fg0))))
     `(ido-only-match ((t (:foreground ,green))))
     `(ido-subdir ((t (:inherit dired-directory))))
     `(ido-virtual ((t (:foreground ,wisteria))))
     `(ido-incomplete-regexp ((t (:inherit warning))))
     `(ido-indicator ((t (:foreground ,fg0 :weight bold))))

     `(vertico-current ((t (:background ,bg1))))
     `(vertico-group-title ((t (:foreground ,quartz1))))
     `(vertico-group-separator ((t (:foreground ,quartz1 :strike-through ,bg2))))

     `(vertico-posframe ((t (:foreground ,fg0 :background ,bg0))))
     `(vertico-posframe-border ((t (:background ,quartz0))))

     `(orderless-match-face-0 ((t (:inherit match))))
     `(orderless-match-face-1 ((t (:inherit match))))
     `(orderless-match-face-2 ((t (:inherit match))))
     `(orderless-match-face-3 ((t (:inherit match))))

     `(compilation-info ((t (:foreground ,quartz1))))
     `(compilation-line-number ((t (:foreground ,quartz1))))
     `(compilation-column-number ((t (:foreground ,quartz1))))
     `(compilation-mode-line-exit ((t (:foreground ,quartz1))))
     `(compilation-warning ((t (:foreground ,yellow))))
     `(compilation-mode-line-run ((t (:foreground ,wisteria))))
     `(compilation-error ((t (:foreground ,red))))
     `(compilation-mode-line-fail ((t (:foreground ,red))))

     `(consult-preview-match ((t (:foreground ,fg0 :background ,quartz0))))
     `(consult-file ((t (:foreground ,fg0))))
     `(consult-highlight-mark ((t (:foreground ,fg0 :background ,bg2))))
     `(consult-highlight-match ((t (:inherit match))))
     `(consult-preview-insertion ((t (:foreground ,fg0 :background ,bg1))))
     `(consult-preview-line ((t (:background ,bg1))))
     `(consult-key ((t (:foreground ,fg0 :background ,bg1))))
     `(consult-help ((t (:foreground ,fg0 :background ,bg1))))
     `(consult-grep-context ((t (:foreground ,quartz1 :background ,bg1))))
     `(consult-line-number ((t (:foreground ,quartz1))))
     `(consult-line-number-prefix ((t (:foreground ,quartz1))))
     `(consult-line-number-wrapped ((t (:foreground ,quartz1))))
     `(consult-narrow-indicator ((t (:foreground ,quartz1))))

     `(mc/cursor-face ((t (:foreground ,bg0 :background ,yellow))))
     `(mc/region-face ((t (:inherit region))))

     `(vr/group-0 ((t (:foreground ,bg0 :background ,green))))
     `(vr/group-1 ((t (:foreground ,bg0 :background ,niagara2))))
     `(vr/group-2 ((t (:foreground ,bg0 :background ,wisteria))))

     `(vr/match-0 ((t (:foreground ,bg0 :background ,quartz1))))
     `(vr/match-1 ((t (:foreground ,bg0 :background ,quartz1))))
     `(vr/match-separator-face ((t (:foreground ,bg0 :background ,red))))

     `(avy-background-face ((t (:background ,bg0))))
     `(avy-lead-face ((t (:foreground ,yellow :background ,bg2))))
     `(avy-lead-face-0 ((t (:foreground ,yellow :background ,bg2))))
     `(avy-lead-face-1 ((t (:foreground ,yellow :background ,bg2))))
     `(avy-lead-face-2 ((t (:foreground ,yellow, :background ,bg2))))

     `(dired-broken-symlink ((t (:foreground ,red :background ,bg0))))
     `(dired-directory ((t (:foreground ,quartz1 :background ,bg0))))
     `(dired-flagged ((t (:foreground ,red :background ,bg0))))
     `(dired-header ((t (:foreground ,niagara2 :background ,bg0))))
     `(dired-ignored ((t (:foreground ,fg0 :background ,bg0))))
     `(dired-mark ((t (:foreground ,quartz1 :background ,bg0))))
     `(dired-marked ((t (:foreground ,yellow :background ,bg0))))
     `(dired-perm-write ((t (:foreground ,fg0 :background ,bg0))))
     `(dired-set-id ((t (:foreground ,fg0 :background ,bg0))))
     `(dired-special ((t (:foreground ,fg0 :background ,bg0))))
     `(dired-symlink ((t (:foreground ,wisteria :background ,bg0))))
     `(dired-warning ((t (:foreground ,yellow :background ,bg0))))

     `(diredfl-symlink ((t (:foreground ,wisteria))))
     `(diredfl-dir-name ((t (:foreground ,quartz1))))
     `(diredfl-dir-heading ((t (:foreground ,niagara2))))
     `(diredfl-file-name ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-file-suffix ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-deletion ((t (:foreground ,red :background ,bg0))))
     `(diredfl-deletion-file-name ((t (:foreground ,red :background ,bg0))))
     `(diredfl-number ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-date-time ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-flag-mark ((t (:foreground ,yellow :background ,bg0))))
     `(diredfl-flag-mark-line ((t (:foreground ,yellow :background ,bg0))))
     `(diredfl-dir-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-read-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-write-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-exec-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-link-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-no-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-autofile-name ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-compressed-file-name ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-compressed-file-suffix ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-ignored-file-name ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-executable-tag ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-other-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-rare-priv ((t (:foreground ,fg0 :background ,bg0))))
     `(diredfl-tagged-autofile-name ((t (:foreground ,fg0 :background ,bg0))))

     `(org-document-title ((t (:inherit outline-1 :height 1.1))))
     `(org-level-1 ((t (:foreground ,quartz1 :height 1.1))))
     `(org-level-2 ((t (:foreground ,niagara2 :height 1.0))))
     `(org-level-3 ((t (:foreground ,wisteria :height 1.0))))
     `(org-level-4 ((t (:foreground ,green :height 1.0))))
     `(org-level-5 ((t (:foreground ,quartz1 :height 1.0))))
     `(org-level-6 ((t (:foreground ,niagara2 :height 1.0))))
     `(org-level-7 ((t (:foreground ,wisteria :height 1.0))))
     `(org-level-8 ((t (:foreground ,green :height 1.0))))
     `(org-link ((t (:foreground ,quartz1 :underline ,quartz1))))
     `(org-todo ((t (:foreground ,red))))
     `(org-done ((t (:foreground ,niagara2 :weight bold))))
     `(org-warning ((t (:foreground ,yellow))))
     `(org-hide ((t (:foreground ,bg0))))
     `(org-special-keyword ((t (:inherit font-lock-comment-face))))
     `(org-drawer ((t (:inherit font-lock-function-name-face))))
     `(org-column ((t (:background ,bg0))))
     `(org-column-title ((t (:background ,bg0 :underline t :weight bold))))
     `(org-archived ((t (:foreground ,fg0 :weight bold))))
     `(org-footnote ((t (:foreground ,niagara2 :underline t))))
     `(org-ellipsis ((t (:foreground ,quartz1))))
     `(org-date ((t (:foreground ,quartz1 :underline t))))
     `(org-sexp-date ((t (:foreground ,quartz1 :underline t))))
     `(org-tag ((t (:weight bold))))
     `(org-list-dt ((t (:weight bold))))
     `(org-agenda-done ((t (:foreground ,niagara2))))
     `(org-headline-done ((t (:foreground ,niagara2))))
     `(org-table ((t (:foreground ,quartz1))))
     `(org-block ((t (:background ,bg0))))
     `(org-block-begin-line ((t (:background ,bg0))))
     `(org-block-end-line ((t (:background ,bg0))))
     `(org-formula ((t (:foreground ,wisteria))))
     `(org-document-info ((t (:foreground ,quartz1))))
     `(org-agenda-structure ((t (:inherit font-lock-comment-face))))
     `(org-agenda-date-today ((t (:foreground ,fg0 :weight bold :slant italic))))
     `(org-scheduled ((t (:foreground ,wisteria))))
     `(org-scheduled-today ((t (:foreground ,quartz1))))
     `(org-scheduled-previously ((t (:foreground ,red))))
     `(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
     `(org-deadline-announce ((t (:foreground ,red))))
     `(org-time-grid ((t (:foreground ,quartz1))))
     `(org-latex-and-related ((t (:foreground ,quartz1))))

     `(markdown-header-face-1 ((t (:foreground ,quartz1))))
     `(markdown-header-face-2 ((t (:foreground ,niagara2))))
     `(markdown-header-face-3 ((t (:foreground ,wisteria))))
     `(markdown-header-face-4 ((t (:foreground ,green))))
     `(markdown-header-face-5 ((t (:foreground ,quartz1))))
     `(markdown-header-face-6 ((t (:foreground ,niagara2))))
     `(markdown-url-face ((t (:foreground ,niagara2))))
     `(markdown-plain-url-face ((t (:foreground ,niagara2))))
     `(markdown-code-face ((t (:foreground ,quartz1))))

     `(git-commit-summary ((t (:foreground ,fg0))))
     `(git-commit-overlong-summary ((t (:foreground ,quartz1))))
     `(git-commit-nonempty-second-line ((t (:foreground ,red))))

     `(magit-header-line ((t (:foreground ,yellow))))
     `(magit-section-heading ((t (:foreground ,yellow))))
     `(magit-branch-remote ((t (:foreground ,green))))
     `(magit-branch-local ((t (:foreground ,niagara2))))
     `(magit-branch-current ((t (:underline ,niagara2 :inherit magit-branch-local))))
     `(magit-diff-added ((t (:foreground ,green))))
     `(magit-diff-added-highlight ((t (:foreground ,green :background ,bg1))))
     `(magit-diff-removed ((t (:foreground ,red))))
     `(magit-diff-removed-highlight ((t (:foreground ,red :background ,bg1))))
     `(magit-diff-base ((t (:foreground ,wisteria :background ,bg0))))
     `(magit-diff-base-highlight ((t (:foreground ,wisteria :background ,bg0))))
     `(magit-diff-context ((t (:foreground ,fg0))))
     `(magit-diff-context-highlight ((t (:foreground ,fg0 :background ,bg0))))
     `(magit-diff-hunk-heading ((t (:foreground ,fg0 :background ,bg1))))
     `(magit-diff-hunk-heading-highlight ((t (:foreground ,fg0 :background ,bg2))))
     `(magit-diff-hunk-heading-selection ((t (:foreground ,fg0 :background ,bg1))))
     `(magit-diff-lines-boundary ((t (:foreground ,wisteria :background ,bg0))))
     `(magit-diff-lines-heading ((t (:foreground ,wisteria :background ,bg0))))
     `(magit-diff-whitespace-warning ((t (:foreground ,red :background ,bg0))))
     `(magit-diff-file-heading-selection ((t (:foreground ,quartz1 :background ,bg0))))
     `(magit-diffstat-added ((t (:foreground ,green))))
     `(magit-diffstat-removed ((t (:foreground ,red))))
     `(magit-process-ok ((t (:foreground ,green))))
     `(magit-process-ng ((t (:foreground ,red))))
     `(magit-log-author ((t (:foreground ,red))))
     `(magit-log-date ((t (:foreground ,quartz1))))
     `(magit-log-graph ((t (:foreground ,bg3))))
     `(magit-log-message ((t (:foreground ,fg0))))
     `(magit-reflog-cherry-pick ((t (:foreground ,green))))
     `(magit-reflog-commit ((t (:foreground ,green))))
     `(magit-reflog-merge ((t (:foreground ,green))))
     `(magit-reflog-reset ((t (:foreground ,red))))
     `(magit-reflog-amend ((t (:foreground ,wisteria))))
     `(magit-reflog-checkout ((t (:foreground ,niagara2))))
     `(magit-reflog-other ((t (:foreground ,quartz1))))
     `(magit-reflog-rebase ((t (:foreground ,wisteria))))
     `(magit-reflog-remote ((t (:foreground ,niagara2))))
     `(magit-sequence-stop ((t (:foreground ,green))))
     `(magit-sequence-drop ((t (:foreground ,wisteria))))
     `(magit-sequence-head ((t (:foreground ,quartz1))))
     `(magit-sequence-part ((t (:foreground ,wisteria))))
     `(magit-signature-good ((t (:foreground ,green))))
     `(magit-signature-bad ((t (:foreground ,red))))
     `(magit-signature-error ((t (:foreground ,red))))
     `(magit-signature-expired ((t (:foreground ,wisteria))))
     `(magit-signature-revoked ((t (:foreground ,wisteria))))
     `(magit-signature-untrusted ((t (:foreground ,niagara2))))
     `(magit-bisect-bad ((t (:foreground ,red))))
     `(magit-bisect-good ((t (:foreground ,green))))
     `(magit-bisect-skip ((t (:foreground ,wisteria))))
     `(magit-mode-line-process-error ((t (:foreground ,red))))
     `(magit-blame-heading ((t (:foreground ,brown :background ,bg1))))
     `(magit-cherry-equivalent ((t (:foreground ,wisteria))))
     `(magit-cherry-unmatched ((t (:foreground ,quartz1))))
     `(magit-dimmed ((t (:foreground ,bg3))))
     `(magit-hash ((t (:foreground ,niagara2))))
     `(magit-refname ((t (:foreground ,brown))))
     `(magit-section-heading-selection ((t (:foreground ,wisteria))))
     `(magit-section-highlight ((t (:background ,bg1))))
     `(magit-tag ((t (:foreground ,wisteria))))

     `(diff-header ((t (:foreground ,fg0 :background ,bg2))))
     `(diff-error ((t (:foreground ,red :background ,bg2))))
     `(diff-file-header ((t (:foreground ,fg0 :background ,bg2))))
     `(diff-hunk-header ((t (:foreground ,fg0 :background ,bg2))))
     `(diff-context ((t (:background ,bg0))))
     `(diff-added ((t (:foreground ,green :background ,bg0))))
     `(diff-removed ((t (:foreground ,red :background ,bg0))))
     `(diff-changed ((t (:foreground ,yellow :background ,bg0))))
     `(diff-refine-added ((t (:background ,bg-green))))
     `(diff-refine-changed ((t (:background ,bg-green))))
     `(diff-refine-removed ((t (:background ,bg-red))))
     `(diff-indicator-added ((t (:foreground ,green))))
     `(diff-indicator-removed ((t (:foreground ,red))))

     `(ediff-current-diff-Ancestor ((t (:foreground ,quartz1 :background ,bg1))))
     `(ediff-current-diff-A ((t (:foreground ,red :background ,bg1))))
     `(ediff-current-diff-B ((t (:foreground ,green :background ,bg1))))
     `(ediff-current-diff-C ((t (:foreground ,yellow :background ,bg1))))
     `(ediff-fine-diff-Ancestor ((t (:foreground ,quartz1 :background ,bg-quartz))))
     `(ediff-fine-diff-A ((t (:foreground ,red :background ,bg-red))))
     `(ediff-fine-diff-B ((t (:foreground ,green :background ,bg-green))))
     `(ediff-fine-diff-C ((t (:foreground ,yellow :background ,bg-yellow))))
     `(ediff-even-diff-Ancestor ((t (:foreground ,quartz1 :background ,bg0))))
     `(ediff-even-diff-A ((t (:foreground ,red :background ,bg0))))
     `(ediff-even-diff-B ((t (:foreground ,green :background ,bg0))))
     `(ediff-even-diff-C ((t (:foreground ,yellow :background ,bg0))))
     `(ediff-odd-diff-Ancestor ((t (:foreground ,quartz1 :background ,bg0))))
     `(ediff-odd-diff-A ((t (:foreground ,red :background ,bg0))))
     `(ediff-odd-diff-B ((t (:foreground ,green :background ,bg0))))
     `(ediff-odd-diff-C ((t (:foreground ,yellow :background ,bg0))))

     `(smerge-upper ((t (:foreground ,red :background ,bg1 :extend t))))
     `(smerge-lower ((t (:foreground ,green :background ,bg1 :extend t))))
     `(smerge-base ((t (:foreground ,quartz1 :background ,bg1 :extend t))))
     `(smerge-markers ((t (:foreground ,quartz0 :background ,bg0 :weight bold :extend t))))
     `(smerge-refined-removed ((t (:foreground ,red :background ,bg-red :extend t))))
     `(smerge-refined-added ((t (:foreground ,green :background ,bg-green :extend t))))
     `(smerge-refined-changed ((t (:foreground ,yellow :background ,bg-yellow :extend t))))

     `(eglot-mode-line ((t (:foreground ,quartz1 :weight medium))))
     `(eglot-highlight-symbol-face ((t (:weight medium))))

     `(flycheck-error ((t (:underline (:style wave :color ,red)))))
     `(flycheck-warning ((t (:underline (:style wave :color ,yellow)))))
     `(flycheck-info ((t (:underline (:style wave :color ,niagara2)))))
     `(flycheck-fringe-warning ((t (:foreground ,yellow))))
     `(flycheck-fringe-error ((t (:foreground ,red))))
     `(flycheck-fringe-info ((t (:foreground ,niagara2))))
     `(flycheck-error-list-warning ((t (:foreground ,wisteria :weight bold))))
     `(flycheck-error-list-error ((t (:foreground ,red :weight bold))))
     `(flycheck-error-list-info ((t (:foreground ,niagara2 :weight bold))))

     `(flymake-error ((t (:underline (:style wave :color ,red)))))
     `(flymake-warning ((t (:underline (:style wave :color ,yellow)))))
     `(flymake-note ((t (:underline (:style wave :color ,niagara2)))))

     `(wgrep-file-face ((t (:background ,bg2))))
     `(wgrep-reject-face ((t (:foreground ,red))))
     `(wgrep-delete-face ((t (:strike-through ,red))))
     `(wgrep-done-face ((t (:foreground ,niagara2))))
     `(wgrep-face ((t (:foreground ,fg0))))

     `(vundo-highlight ((t (:foreground ,green))))
     `(vundo-saved ((t (:foreground ,yellow))))
     `(vundo-last-saved ((t (:foreground ,red))))

     `(minibuffer-depth-indicator ((t (:background ,bg1))))
     `(persp-selected-face ((t (:foreground ,quartz1))))
     `(marginalia-documentation ((t (:foreground ,fg0 :italic t))))

     `(p4-action-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-branch-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-change-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-client-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-depot-add-face ((t (:foreground ,green :background ,bg0))))
     `(p4-depot-branch-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-depot-delete-face ((t (:foreground ,red :background ,bg0))))
     `(p4-depot-edit-face ((t (:foreground ,yellow :background ,bg0))))
     `(p4-description-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-filespec-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-form-comment-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-form-keyword-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-heading-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-job-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-label-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-link-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-revision-face ((t (:foreground ,fg0 :background ,bg0))))
     `(p4-user-face ((t (:foreground ,fg0 :background ,bg0))))

     `(eshell-prompt ((t (:foreground ,quartz1))))
     `(eshell-ls-archive ((t (:foreground ,fg0))))
     `(eshell-ls-backup ((t (:foreground ,brown))))
     `(eshell-ls-clutter ((t (:foreground ,wisteria))))
     `(eshell-ls-directory ((t (:foreground ,niagara2))))
     `(eshell-ls-executable ((t (:weight bold))))
     `(eshell-ls-missing ((t (:foreground ,red))))
     `(eshell-ls-product ((t (:foreground ,red))))
     `(eshell-ls-readonly ((t (:foreground ,fg0))))
     `(eshell-ls-special ((t (:foreground ,wisteria))))
     `(eshell-ls-symlink ((t (:foreground ,wisteria))))
     `(eshell-ls-unreadable ((t (:foreground ,red))))

     `(term-color-black ((t (:foreground ,bg3 :background ,bg1))))
     `(term-color-red ((t (:foreground ,red :background ,red))))
     `(term-color-green ((t (:foreground ,green :background ,green))))
     `(term-color-blue ((t (:foreground ,niagara0 :background ,niagara0))))
     `(term-color-yellow ((t (:foreground ,yellow :background ,yellow))))
     `(term-color-magenta ((t (:foreground ,wisteria :background ,wisteria))))
     `(term-color-cyan ((t (:foreground ,quartz1 :background ,quartz1))))
     `(term-color-white ((t (:foreground ,fg0 :background ,fg0))))

     `(ansi-color-black ((t (:foreground ,bg3 :background ,bg1))))
     `(ansi-color-red ((t (:foreground ,red :background ,red))))
     `(ansi-color-yellow ((t (:foreground ,yellow :background ,yellow))))
     `(ansi-color-green ((t (:foreground ,green :background ,green))))
     `(ansi-color-blue ((t (:foreground ,niagara2 :background ,niagara2))))
     `(ansi-color-magenta ((t (:foreground ,wisteria :background ,wisteria))))
     `(ansi-color-cyan ((t (:foreground ,quartz1 :background ,quartz1))))
     `(ansi-color-white ((t (:foreground ,fg0 :background ,fg0))))
     `(ansi-color-bright-black ((t (:foreground ,bg3 :background ,bg1))))
     `(ansi-color-bright-red ((t (:foreground ,red :background ,red))))
     `(ansi-color-bright-yellow ((t (:foreground ,yellow :background ,yellow))))
     `(ansi-color-bright-green ((t (:foreground ,green :background ,green))))
     `(ansi-color-bright-blue ((t (:foreground ,niagara2 :background ,niagara2))))
     `(ansi-color-bright-magenta ((t (:foreground ,wisteria :background ,wisteria))))
     `(ansi-color-bright-cyan ((t (:foreground ,quartz1 :background ,quartz1))))
     `(ansi-color-bright-white ((t (:foreground ,fg0 :background ,fg0))))

     `(transient-heading ((t (:foreground ,fg0))))
     `(transient-key ((t (:foreground ,quartz1))))
     `(transient-key-stack ((t (:foreground ,quartz1))))
     `(transient-key-stay ((t (:foreground ,niagara2))))
     `(transient-key-recurse ((t (:foreground ,niagara2))))
     `(transient-key-exit ((t (:foreground ,niagara2))))
     `(transient-argument ((t (:foreground ,quartz1))))
     `(transient-value ((t (:foreground ,quartz1))))
     `(transient-inactive-argument ((t (:foreground ,bg4))))
     `(transient-inactive-value ((t (:foreground ,bg3))))
     `(transient-unreachable ((t (:foreground ,bg3))))
     `(transient-unreachable-key ((t (:foreground ,bg3))))
     `(transient-nonstandard-key ((t (:foreground ,wisteria))))
     `(transient-mismatched-key ((t (:foreground ,red))))
     `(transient-enabled-suffix ((t (:foreground ,quartz1))))
     `(transient-disabled-suffix ((t (:foreground ,bg4))))
     `(transient-separator ((t (:foreground ,bg4))))
     `(transient-key-return ((t (:foreground ,yellow))))))

  (defface mode-line-buffer-id-inactive
    `((t (:inherit mode-line-buffer-id
                   :foreground ,(gruber-material--lookup palette 'gruber-material-dark-quartz0)
                   :background ,(gruber-material--lookup palette 'gruber-material-dark-bg0))))
    "Face for buffer name in inactive windows."))

(defmacro gruber-material-deftheme (name palette)
  `(progn
     (deftheme ,name ,(format "%s" name))
     (gruber-material--apply-faces ',name ,palette)
     (when load-file-name
       (add-to-list 'custom-theme-load-path
                    (file-name-as-directory (file-name-directory load-file-name))))
     (provide-theme ',name)))

(provide 'gruber-material-core)
